# Generated by Django 5.0.6 on 2024-06-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExPense_Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
